NUMPY EXERCISES

In [1]:
import numpy as np

In [3]:
list1 = [0, 1, 2, 3, 4]

array1 = np.array(list1)
array1

array([0, 1, 2, 3, 4])

In [5]:
np.zeros((4,3)).astype('int')
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.zeros((3,3), dtype=float)
np.zeros((3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [8]:
# 3 pieces of 8x8
np.zeros([3,8,8])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0

In [9]:
# four dimensional 3 pieces of 8 pieces of 8x5 array
x=np.zeros([3,8,8,5])
x

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],



In [13]:
np.ones((2, 3, 5))
np.ones((2, 3, 3, 5))
np.ones((3, 3))*13

array([[13., 13., 13.],
       [13., 13., 13.],
       [13., 13., 13.]])

In [19]:
np.full((3,3),"ugur")
np.full(12,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [27]:
np.empty((3,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.60218491e-306],
       [3.52936832e-317, 1.39067116e-308]])

In [29]:
np.eye(6,k=-1)
np.eye(6,k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
np.arange(0, 1000, 13)
np.arange(18, 1000, 18)
np.arange(15, 46, 3)
np.arange(20)
np.arange(0, 5, 0.5)
np.arange(-10,100,5)

array([-10,  -5,   0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,
        55,  60,  65,  70,  75,  80,  85,  90,  95])

In [41]:
np.arange(100, 0, -10)
a = np.arange(24)
# -1 i python kendi hesaplar.
a.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
np.linspace(0,15, 4)
np.linspace(0,300,100, endpoint=False)
np.linspace(0,300,101)
np.linspace(0, 100, 51)
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [52]:
np.random.randint(-1000,1000, 25)
np.random.randint(0, 10, 20)
np.random.randint(0, 100, 20)

array([13,  9, 76, 48, 49, 38, 74, 71,  1, 79, 25, 11, 52, 51, 22, 54, 76,
       65, 98, 48])

In [56]:
# mean, std, size
np.random.normal(10, 20, (2,2))
np.random.normal(10, 30, (5, 5))

array([[-13.38022048,  65.09686092,   1.31109761,  15.56213591,
         10.83896046],
       [-27.22235271,  43.19730709,  20.49582149,  57.49367771,
         -5.15212705],
       [-34.05897308,  38.60176856, -19.50451571,  16.95282217,
         32.2852883 ],
       [ 10.27059788,   1.05127315,   5.19696066,  53.52407798,
         -3.77719391],
       [ -3.9636827 ,   6.28869408, -14.43016906, -10.73597719,
          5.4614022 ]])

In [59]:
np.random.randn(5,2)
np.random.randn(5)*10

array([-11.31222614,   2.15896382,  -1.83103188,  -5.09785428,
        -9.548289  ])

In [60]:
x=np.array(["4"],dtype="int32")

In [64]:
a=np.arange(1,7) 
x=a[np.newaxis,:]
x.shape

(1, 6)

In [70]:
a = np.arange(20).reshape(5, 4)
np.vsplit(a, [2, 3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [74]:
a=np.arange(1,13).reshape(3,4)
a
a[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [77]:
a = np.arange(1, 13).reshape(3, 4)
print(a)
b = a[1, (0, 2)]
b

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([5, 7])

In [78]:
oynama = np.random.randint(0, 100, (5, 5))
oynama

array([[18, 75, 89, 58, 14],
       [64, 22, 40, 40, 66],
       [88, 41, 37, 59, 94],
       [61, 77, 88, 25, 88],
       [77, 14, 25, 43, 21]])

In [84]:
oynama > 40
oynama == 88
oynama != 88
lte_sixty = oynama <= 60
oynama[lte_sixty]

array([18, 58, 14, 22, 40, 40, 41, 37, 59, 25, 14, 25, 43, 21])

In [91]:
oynama % 2
oynama // 2
oynama * 3
oynama // 5
oynama + 15
np.square(oynama)
np.sqrt(oynama)

array([[4.24264069, 8.66025404, 9.43398113, 7.61577311, 3.74165739],
       [8.        , 4.69041576, 6.32455532, 6.32455532, 8.1240384 ],
       [9.38083152, 6.40312424, 6.08276253, 7.68114575, 9.69535971],
       [7.81024968, 8.77496439, 9.38083152, 5.        , 9.38083152],
       [8.77496439, 3.74165739, 5.        , 6.55743852, 4.58257569]])

In [100]:
oynama[2, 2]
oynama[:, 4]
oynama[:, [0, 2, 4]]
oynama[0, [0, 2, 4]]
oynama[[0, 2, 4]]
# diagonal
oynama[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
oynama[[0,2,4],1:3]
np.concatenate((oynama[:,4],oynama[4,:]))
# oynama[[4],[4]]

array([21])

In [65]:
a=np.arange(1,21).reshape(4,5) 
np.sum(a,axis=0).shape

(5,)

In [66]:
a=np.arange(1,21).reshape(4,5)

np.all(a>8,axis=1)

array([False, False,  True,  True])

In [69]:
a=np.arange(1,21).reshape(4,5)
# a
np.any(a>4,axis=0)

array([ True,  True,  True,  True,  True])

## SADIK TURAN EXERCISE

In [96]:
new_array = np.array([10, 15, 30, 45, 60])
# new_array
linear = np.arange(5,16)
linear
fives = np.arange(50, 101, 5)
fives
np.zeros(10)
np.ones(10)
np.linspace(0, 100, 6)
np.random.randint(10, 30, 5)
np.random.randn(10)
matrix_1 = np.random.randint(10, 50, (3, 5))
matrix_1

array([[42, 14, 21, 44, 15],
       [28, 13, 17, 11, 41],
       [34, 48, 32, 16, 44]])

In [98]:
matrix_1.sum(axis=1)  # row sum
matrix_1.sum(axis=0)  # column sum

array([104,  75,  70,  71, 100])

In [102]:
matrix_1.max()
matrix_1.min()
matrix_1.mean()

28.0

In [105]:
matrix_1.argmax()
matrix_1.argmin()

8

In [112]:
indexing = np.arange(10, 21)
indexing[:3]
indexing[::-1]
matrix_1[0,:]
matrix_1[0]
matrix_1[1,2]
matrix_1[:,0]



array([42, 28, 34])

In [113]:
matrix_1**2

array([[1764,  196,  441, 1936,  225],
       [ 784,  169,  289,  121, 1681],
       [1156, 2304, 1024,  256, 1936]])

In [118]:
filter_matrix = np.random.randint(-50, 50, 40)
filter_matrix

array([-16,  45,  30, -42, -49, -30,  37,  26, -18,   6,  21,  43,  27,
       -17,  11, -17, -23, -16,  15,  17,  -3, -43, -35, -43,  41, -20,
        46, -49,  -2, -49,  12, -12, -34,  32,  -8,   2,   0, -38,  38,
        25])

In [126]:
even_filter = filter_matrix % 2 == 0
positive_filter = filter_matrix > 0 
# even_filter = all(filter_matrix > 0, filter_matrix % 2 == 0)
# even_filter
last_filter = np.logical_and(positive_filter,even_filter)
filter_matrix[last_filter]

array([30, 26,  6, 46, 12, 32,  2, 38])