ARRAYS

In [1]:
import numpy as np
import numpy.random as rd

list1=[0,1,2,3]

array1=np.array(list1)
array1

array([0, 1, 2, 3])

In [2]:
my_array=np.array([4,3,2,1])
my_array

array([4, 3, 2, 1])

In [3]:
list2 = [10, 11, 12, 13]
comb_list = [list1, list2]
comb_list

[[0, 1, 2, 3], [10, 11, 12, 13]]

In [5]:
comb_array = np.array(comb_list)
comb_array
comb_array.dtype

dtype('int32')

In [6]:
np.array(comb_list, dtype="float")

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.]])

In [8]:
np.zeros(6)
np.zeros((3,4))

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10)
zeros_array=np.zeros((5,2))
zeros_array
zeros_array.dtype
zeros_array.astype('int')

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [12]:
np.ones((2,4)) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.empty((3,4)).dtype
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# diagonal
np.eye(5)
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [19]:
np.arange(10,50,5)
ondalik=np.arange(0,2,0.2)
ondalik
esit_aralik=np.linspace(0,4,11)
esit_aralik

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. ])

In [22]:
# range auto array
np.arange(5)
np.arange(0,200,5)
np.linspace(0,5,11)


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

RANDOM

In [30]:
rd.randint(1,1000)
rd.randn(10)
rd.randint(1,1000,10)
rd.rand(100)*100

# second method
array=np.random.randint(0,10,10)
array

array([5, 6, 3, 6, 9, 3, 2, 4, 8, 6])

In [33]:
# randint(start,end,count)
c = np.random.randint(1, 50, 15)
c

array([49, 22,  9, 29, 15, 35, 10,  6, 16, 38,  2, 42, 49,  5,  8])

In [36]:
# normal dağılım:
n = np.random.randn(2, 5) * 5
n

array([[ 1.04423042,  5.56628524, -1.0999114 , -7.18269008, -3.30253879],
       [ 9.72858182,  5.66180554,  7.11873549, -1.11717245,  8.17395967]])

In [38]:
rast=np.random.rand(3,4)
rast
normal_dagilim=np.random.randn(2,5)
normal_dagilim

array([[ 0.15696924, -2.00215683,  1.50237415, -1.63038356,  0.58146076],
       [-0.33287224, -0.71475613,  0.57863016,  0.01972872, -1.80857975]])

In [42]:
# reshape the array size
array=array.reshape(2,5)
array

array([[5, 6, 3, 6, 9],
       [3, 2, 4, 8, 6]])

In [45]:
your_array=np.arange(50)
your_array.shape= 2,-1,5  # -1, araya en uygunu yerleştir diyor.
your_array.shape
your_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [51]:
y = np.arange(24)
y
y.reshape(6,4)
y.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

ARITHMETICAL OPS

In [53]:
array2 = rd.randint(1, 5, 20)
array2 = array2.reshape(4, 5)
array2

array([[3, 1, 2, 1, 4],
       [3, 4, 4, 1, 3],
       [2, 4, 1, 2, 3],
       [3, 2, 4, 3, 4]])

In [61]:
# element wise
array2 + array2
array2 - array2
array2 * array2
array2 * 10
1 / array2
array2 // 2

array([[1, 0, 1, 0, 2],
       [1, 2, 2, 0, 1],
       [1, 2, 0, 1, 1],
       [1, 1, 2, 1, 2]], dtype=int32)

In [65]:
birinci = np.array([20, 40, 60, 80])
ikinci = np.array([0, 1, 2, 3])
toplam = birinci + ikinci
toplam
toplam ** 2

array([ 400, 1681, 3844, 6889])

In [68]:
birinci > 50
birinci += 10
birinci

array([ 40,  60,  80, 100])

In [12]:
rasgele=np.random.random(12)
print(rasgele)
rasgele.max()
rasgele.min()
rasgele.sum()

7.8444695121007095

In [16]:
# yatay ve dikey toplama:
# dikey-sütun toplama
toplama=np.arange(15).reshape(3,5)
print(toplama)
toplama.sum(axis=0)

# yatay toplama
toplama.sum(axis=1)

toplama.max(axis=1)

toplama.cumsum(axis=1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [21]:
# istatistiksel işlemler
k=np.random.random(10)

k.mean()
# medyan
np.median(k)
# standart sapma
np.std(k)
# varyans
np.var(k)
# kopyası :)
kopya=k.copy()



In [22]:
# unique fonksiyonu

sehir=np.array(["ankara","istanbul","bursa","izmir","ankara","istanbul","bursa"])

np.unique(sehir)

array(['ankara', 'bursa', 'istanbul', 'izmir'], dtype='<U8')

SELECTION AND INDEXING

In [78]:
dizim= np.arange(15)
dizim[0]
dizim[-1]
dizim[5:]
dizim[:]
dizim[2:12:3]
dizim[0:5]=20
dizim

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [83]:
part_dizim=dizim[:3]
part_dizim[:]=11
part_dizim

# fully independent
copy_dizim=dizim[0:5].copy()
copy_dizim

array([11, 11, 11, 20, 20])

In [89]:
iki_boyutlu=np.arange(9).reshape(3,3)
iki_boyutlu

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
iki_boyutlu[1,1]
# original!
iki_boyutlu[:3,:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [96]:
diger_dizi=np.arange(25).reshape(5,5)
diger_dizi

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [98]:
diger_dizi[[0,2]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [100]:
diger_dizi[:,[0,2]]

array([[ 0,  2],
       [ 5,  7],
       [10, 12],
       [15, 17],
       [20, 22]])

In [22]:
single=np.arange(10)**2
single[3]
single[3:6]
single[4]=1000

In [23]:
for i in single:
    print(i*2)

0
2
8
18
2000
50
72
98
128
162


In [11]:
# multi dimension
multi=np.random.random(16)
multi.reshape(4,4)



array([[0.08353913, 0.54591738, 0.51712559, 0.09733484],
       [0.95043029, 0.14410049, 0.35714592, 0.97473001],
       [0.27729   , 0.79369293, 0.35437111, 0.79077782],
       [0.25979962, 0.30525603, 0.39237663, 0.62057166]])

In [33]:
# tekrar tek satırlı hale getirmek için ravel
# multi.ravel()

array([0.07134647, 0.75953004, 0.79395777, 0.07847746, 0.38219248,
       0.00459844, 0.91979563, 0.33772214, 0.23401716, 0.63442721,
       0.99526878, 0.68936092, 0.71929485, 0.06765775, 0.64340525,
       0.33054598])

In [12]:
multi[:,3]
multi[0:2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [15]:
for satir in multi.flat:
    print(satir)

0.08353912772402627
0.5459173771532919
0.5171255862271024
0.09733484281473459
0.9504302931771085
0.14410049499661604
0.3571459157871407
0.9747300132002736
0.2772900003227967
0.7936929346107239
0.3543711069850952
0.7907778170739049
0.2597996193282094
0.30525603241563937
0.39237662918284777
0.6205716646321413


In [ ]:
for i in np.ndenumerate(multi):
    print(i)

In [19]:
# yatay birleştirme
first=np.array([2,3])
second=np.array([5,6])

np.hstack((first,second))

# dikey birleştirme
fourth=np.vstack((first,second))

array([[2, 3],
       [5, 6]])

In [24]:
third=np.array([[7,8],[9,10]])

np.concatenate((third,fourth),axis=0)

NameError: name 'fourth' is not defined

In [104]:
# filtering, amazing!
array>1
filter_array=array>1
array[filter_array]
array[array>2]

array([5, 6, 8, 8])

BUILT IN  FUNCTIONS

In [9]:
ornek= np.arange(15).reshape(5,3)
ornek.sum()
ornek.sum(axis=1) # along column
ornek.sum(axis=0) # along row
ornek

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [12]:
ornek.max()
ornek.max(axis=0) # along row
ornek.max(axis=1) # along column
ornek.argmax(axis=1) # location in their list

array([2, 2, 2, 2, 2], dtype=int64)

In [15]:
c.max()
c.min()
c.argmax() # indeksini döndürür
c.argmin() # indeksi

8

In [13]:
ornek.min(axis=1)

array([ 0,  3,  6,  9, 12])